---

topic:
title:
# A list of hh_mm time formats [avoids jekyll auto-conversion].
# Only days with scheduled items get a start time.
# Days which can't be matched will use the first entry.
start_times:
  - 09_00
venue:
address:
country:
language:
latitude:
longitude:
start_date:
instructors: []
helpers: []
instructor_emails: []
collaborative_notes:
eventbrite:

# list of files in path _includes/intro/*.md. .html files cannot be customised and are always included
optional_intro_sections:
  - requirements
  - accessibility

# list of files in _includes/install_instructions to use in the setup page
setup_files:

setup_files_help: >-
  List of setup guides to include

kind: workshop
ukrn_email: ORT@ukrn.org
repository: <USERNAME>/<PROJECT>
carpentries_site: https://carpentries.org/
pre_survey: https://carpentries.typeform.com/to/wi32rS?slug=
post_survey: https://carpentries.typeform.com/to/UgVdRQ?slug=

collections:
  episodes:
    output: true
    permalink: /:path/index.html
  episodes_rmd:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

exclude:
  - Makefile
  - bin/
  - .Rproj.user/
highlighter: rouge

ukrn-wb:
  - fields:
      - topic:
          - type: string
          - help: >-
              The topic is used to search for pre-existing lessons you can include in your workshop
          - properties:
              - required
      - title:
          - type: string
          - help: >-
              The title should let people know the most important information - where the workshop is and what it covers
          - properties:
            - required
      - start_times:
          - type: time
          - help: >-
              A list of start times for each day of the workshop. If shorter than the number of days, remaining days will use the first entry
          - properties:
              - array
              - required
              - format:
                  - hours_minutes
      - venue:
          - type: string
          - help: >-
              The brief name of the institution that hosts the workshop without address (e.g., "Euphoric State University")
          - properties:
      - address:
          - type: string
          - help: >-
              The full street address of workshop (e.g., "Room A, 123 Forth Street, Blimingen, Euphoria"), videoconferencing URL, or 'online'
          - properties:
      - country:
          - type: string
          - help: >-
              Country code for the institution that hosts the workshop
          - properties:
              - iso-639-1
      - language:
          - type: string
          - help: >-
              Language code for the language the workshop will be conducted in
          - properties:
              - iso-3166-1-alpha-2
      - latitude:
          - type: number
          - help: >-
              Latitude of workshop venue (use <a href="https://www.latlong.net/">https://www.latlong.net"</a>)
          - properties:
              - latitude
      - longitude:
          - type: number
          - help: >-
              Longitude of workshop venue (use <a href="https://www.latlong.net/">https://www.latlong.net"</a>)
          - properties:
              - longitude
      - start_date:
          - type: date
          - help: >-
              Date the workshop starts
          - properties:
              - format:
                  - years_months_days
      - instructors:
          - type: string
          - help: >-
              Instructor name(s)
          - properties:
              - array
              - required
      - helpers:
          - type: string
          - help: >-
              Helper name(s)
          - properties:
              - array
      - instructor_emails:
          - type: string
          - help: >-
              Instructor email address(es) for questions/comments/feedback
          - properties:
              - array
              - email
      - collaborative_notes:
          - type: string
          - help: >-
              URL for the workshop collaborative notes, e.g. an Etherpad or Google Docs document
          - properties:
      - eventbrite:
          - type: string
          - help: >-
              The alphanumeric key for Eventbrite registration, e.g., "1234567890AB"
          - properties:
      - optional_intro_sections:
          - type: filename
          - help: >-
              Optional introductory sections which can be included on the homepage and customised
          - properties:
              - array
              - directories:
                  - _includes/intro
              - filetypes:
                  - md
      - setup_files:
          - type: filename
          - help: >-
              List of setup guides to include on the homepage
          - properties:
              - array
              - directories:
                  - _includes/install_instructions
              - filetypes:
                  - md
