---
workshop-topic: TOPIC NOT SET
title: My workshop
kind: workshop
repository: <USERNAME>/<PROJECT>
email: ORT@ukrn.org
amy_site: https://amy.carpentries.org
carpentries_github: https://github.com/carpentries
carpentries_pages: https://carpentries.github.io
carpentries_site: https://carpentries.org/
dc_site: https://datacarpentry.org
example_repo: https://github.com/carpentries/lesson-example
example_site: https://carpentries.github.io/lesson-example
lc_site: https://librarycarpentry.org/
swc_github: https://github.com/swcarpentry
swc_pages: https://swcarpentry.github.io
swc_site: https://software-carpentry.org
template_repo: https://github.com/carpentries/styles
training_site: https://carpentries.github.io/instructor-training
workshop_repo: https://github.com/carpentries/workshop-template
workshop_site: https://carpentries.github.io/workshop-template
pre_survey: https://carpentries.typeform.com/to/wi32rS?slug=
post_survey: https://carpentries.typeform.com/to/UgVdRQ?slug=
start_time: 0
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
highlighter: rouge
